[package]
name = "pikolor"
version = "0.1.0"
edition = "2021"

[dependencies]
ashpd = "0.9.1"
futures = "0.3.30"
# tokio = { version = "1.39.2", features = ["full"] }

# [dependencies.async-std]
# version = "1.7.0"
# features = ["attributes"]
